# Generated by Django 4.2.3 on 2023-08-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_document',
            field=models.IntegerField(null=True, unique=True, verbose_name='numero de identificacion'),
        ),
    ]
