# Generated by Django 4.2.3 on 2023-08-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employed', '0004_alter_user_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad')], default=('CC', 'Cedula de Ciudadania'), max_length=50, verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_one',
            field=models.CharField(max_length=20, null=True, verbose_name='telefono 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_two',
            field=models.CharField(max_length=20, null=True, verbose_name='telefono 2'),
        ),
    ]
