# Generated by Django 4.2.3 on 2023-08-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_product_unit_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='numero factura')),
                ('created_at', models.DateField(verbose_name='fecha')),
                ('expiration_at', models.DateField(verbose_name='vencimiento')),
                ('pay_at', models.CharField(choices=[('30', 'credito 30 dias'), ('45', 'credito 45 dias'), ('15', 'credito 15 dias'), ('Co', 'contado')], default=('30', 'credito 30 dias'), max_length=50, verbose_name='forma de pago')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='empresa')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='direccion')),
                ('contact', models.CharField(max_length=50, null=True, verbose_name='nombre de contacto')),
                ('phonenumber', models.CharField(default='669999909', max_length=20, unique=True, verbose_name='telefono')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='creacion')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='creacion')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('created_at', models.DateField(verbose_name='created')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.invoice', verbose_name='invoices')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.providers', verbose_name='providers'),
        ),
    ]
