# Generated by Django 4.2.3 on 2023-07-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='numero factura')),
                ('created_at', models.DateField(verbose_name='fecha')),
                ('expiration_at', models.DateField(verbose_name='vencimiento')),
                ('pay_at', models.CharField(choices=[('30', 'credito 30 dias'), ('45', 'credito 45 dias'), ('15', 'credito 15 dias'), ('Co', 'contado')], default=('30', 'credito 30 dias'), max_length=50, verbose_name='forma de pago')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='empresa')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='direccion')),
                ('contact', models.CharField(max_length=50, verbose_name='nombre de contacto')),
                ('phonenumber', models.CharField(max_length=20, unique=True, verbose_name='telefono')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
    ]
