# Generated by Django 4.2.3 on 2023-07-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_category'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.invoice', verbose_name='invoices')),
                ('product', models.ManyToManyField(to='inventory.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'ProductInvoice',
                'verbose_name_plural': 'ProductInvoices',
            },
        ),
    ]
