# Generated by Django 4.2.3 on 2023-07-20 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_category'),
        ('shopping', '0002_productinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinvoice',
            name='product',
        ),
        migrations.AddField(
            model_name='productinvoice',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='products'),
            preserve_default=False,
        ),
    ]
