# Generated by Django 4.2.3 on 2023-08-02 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_order_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('utility', models.CharField(choices=[(0, '30 %'), (1, '20 %'), (2, '15 %'), (3, '10 %'), (4, 'No aplica')], max_length=50, verbose_name='utilidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.order', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
    ]
