# Generated by Django 4.2.3 on 2023-08-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_priceproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceproducts',
            name='utility',
            field=models.CharField(choices=[('precio 1', '30 %'), ('precio 2', '20 %'), ('precio 3', '15 %'), ('precio 4', '10 %'), ('No', 'No aplica')], max_length=50, verbose_name='utilidad'),
        ),
    ]
