# Generated by Django 4.2.3 on 2023-08-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_priceproducts_utility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceproducts',
            old_name='product',
            new_name='order',
        ),
    ]
