# Generated by Django 4.2.3 on 2023-08-03 20:22

from django.db import migrations, models
import django.db.models.deletion
import shopping.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_rename_product_priceproducts_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=shopping.models.get_number_pay, max_length=50, verbose_name='comprobante')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='saldo')),
                ('created_at', models.DateField(verbose_name='created_at')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.invoice', verbose_name='pay')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
