# Generated by Django 4.2.3 on 2023-08-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_payment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='way_to_pay',
            field=models.CharField(choices=[('30', 'credito 30 dias'), ('45', 'credito 45 dias'), ('15', 'credito 15 dias'), ('Co', 'contado')], default='efectivo', max_length=50, verbose_name='forma de pago'),
            preserve_default=False,
        ),
    ]
